name: eComscan
author: Sansec

inputs:
  key:
    description: 'License key'
    default: 'trial'
    required: false
  directory:
    description: 'Directory to scan'
    default: '${{ github.workspace }}'
    required: false

runs:
  using: 'composite'
  steps:
  - uses: actions/checkout@v4
  - run: wget https://ecomscan.com/downloads/linux-amd64/ecomscan
    shell: bash
  - run: chmod +x ecomscan
    shell: bash
  - run: |
      output=$(./ecomscan --key=${{ inputs.key }} --format=csv ${{ inputs.directory }})
      if [ -n "$output" ]; then
        exit 1
      fi
    shell: bash
