name: Setup Magento Store

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-magento-store:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mage-os/github-actions/setup-magento@main
        with:
          php-version: 8.1
          tools: composer:v2
          mode: store
          working-directory: $GITHUB_WORKSPACE
          magento_version: 2.4.7

      - run: composer install
        name: Composer install
        shell: bash
        working-directory: ${{ steps.setup-magento.outputs.path }}
